Use inherited sharing for TriggerHandlerDispatcher
SCWells72/sirono-common pull request #17
Opened 2021-12-08 22:33 UTC by phelpsjackson

2021-12-09 15:23 UTC, SCWells72 commented
Hi, @phelpsjackson. I hope this finds you doing well. This change makes sense, but before it gets folded into the main class library I'd like to see unit tests that verify the behavior when used with `TriggerHandlerFactory` implementations that use `with sharing` and `without sharing` sharing models to confirm lack of access and access to objects respectively. If you want to provide such unit tests, that'd be great, but if not I'll take a stab at them when I get a chance and then merge this.

2021-12-10 05:34 UTC, phelpsjackson commented
@SCWells72 I added a couple of tests, but it seems pretty contrived.  If you have better ideas, let me know.

2021-12-10 14:42 UTC, SCWells72 commented
Thanks, @phelpsjackson. I probably won't get a chance to take a look today but will do so next week.

2022-01-10 22:40 UTC, SCWells72 requested changes
Overall this looks great, Phelps. I like the approach, specifically that it doesn't require test triggers to be added to exercise this logic. I included a few recommendations for small changes in this review, but the main outstanding concern is that the tests don't pass for me. This also raises the point that I should add some kind of CI mechanism to this project to auto-validate PRs and builds, but that's probably something for a later day...

2022-01-10 22:40 UTC, SCWells72 commented on src/classes/TriggerHandlerDispatcher.cls
> +    public static void mock(TriggerOperation operationType) {
This can/should be declared as `@TestVisible private` instead of `public`

2022-01-10 22:40 UTC, SCWells72 commented on src/classes/TriggerHandlerDispatcher.cls
> +        if (!Test.isRunningTest()) {
This entire condition can be replaced with:

```java
Assert.isTrue(Test.isRunningTest(), 'TriggerHandlerDispatcher may only be mocked in a test.');
```

2022-01-10 22:40 UTC, SCWells72 commented on src/classes/TriggerHandlerDispatcher.cls
> +        return mockOperationType != null ? true : Trigger.isExecuting;
Not sure if it makes it any more clear, but this condition can be simplified to `(mockOperationType != null) || Trigger.isExecuting`.

2022-01-10 22:40 UTC, SCWells72 commented on test-src/classes/TriggerHandlerDispatcherTest.cls
> +                Assert.fail('Exception expected.');
When I run this locally, this test fails at this point. I'm executing it in a scratch org that was created for the sole purpose of verifying these changes. Do you perhaps have some authorization config in your test org that's causing this the test to pass for you where it doesn't in a vanilla scratch org? I can investigate further on my side if you're not sure.

2023-11-01 02:41 UTC, closed without merging